#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>

#
#Add custom config directory for Prezto
#

fpath=($HOME/.zsh/prezto-themes $fpath)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file ($HOME/.zsh/zsh.d/*.zsh) source $config_file

#source $HOME/.LS_COLORS/ls_colors.zsh

export ANDROID_HOME=/Users/Realignist/android-sdk

alias vi="vim"
alias ls="ls -al"
eval $(thefuck --alias)

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home

export NVM_DIR="/Users/Realignist/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:/usr/local/opt/go/libexec/bin:/usr/local/opt/go/gopath/bin:$GOROOT/bin:/Users/Realignist/Workspace/bin
export GOPATH=/usr/local/opt/go/gopath:/User/Realignist/Workspace

export GPG_TTY=$(tty)
