#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>

#
#Add custom config directory for Prezto
#

fpath=($HOME/.zsh/prezto-themes $fpath)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file ($HOME/.zsh/zsh.d/*.zsh) source $config_file

#source $HOME/.LS_COLORS/ls_colors.zsh

export ANDROID_HOME=/Users/Realignist/android-sdk

alias vi="vim"
alias ls="ls -al"
eval $(thefuck --alias)

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home

export NVM_DIR="/Users/Realignist/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

alias staging="ssh -i ~/frip-server.pem ubuntu@ec2-52-78-3-3.ap-northeast-2.compute.amazonaws.com"
alias staging_test="NODE_ENV=staging slc run"
